### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by YJonmo** [jhu-saw/sawNDITracker#11]
Hi there,

Thanks for this open work.

I am a bit new to Linux. 
I think I need to install this repo first in order to be able to use it?
So I did:
mkdir build
cd build
cmake ../
make 
sudo make install
sudo ldconfig

So now how can I run this? I don't know what I should type on terminal.
I am trying to communicate with a NDI Aurora tool tracker. 

Cheers,
Jacob

**Comment by adeguet1** [comment]
Closing this, duplicate post, see #5
