### ISSUE TITLE
AURORA+ROS : Error #3: NDI: parsing TX result failed, expected line feed

### ISSUE THREAD

**Issue by moe-sani** [jhu-saw/sawNDITracker#6]
Hi,
thanks for the nice program!
I have used the package with configration file for the Polaris system and it works fine. But the same program does not work well  with the aurora system!
it connects very well, and it shows the frames, but when i hit the track button, following error appears.
here is the error:
10:52:21 Status #1: NDI: found serial port: /dev/ttyUSB0
10:52:22 Status #2: NDI: device found on port: /dev/ttyUSB0
10:52:23 Status #3: NDI: SetSerialPortSettings succeeded
10:52:24 Status #4: NDI: device initialized
10:52:24 Status #5: NDI: command VER 0 returned:
Aurora Control Firmware
NDI S/N: D4-04652
Characterization Date: 2016-12-21
Freeze Tag: AURORA Rev 008
Freeze Date: 2013-07-25
(C) Northern Digital Inc.

10:52:24 Status #6: NDI: command VER 3 returned:
ERROR23
10:52:24 Status #7: NDI: command VER 4 returned:
Aurora Control Firmware
NDI S/N: D4-04652
Characterization Date: 2016-12-21
Freeze Tag: AURORA Rev 008.000
Freeze Date: 2013-07-25
(C) Northern Digital Inc.

10:52:24 Warning #1: NDI: device firmware is not what we're expecting, got: 013.  It might still work
10:52:25 Status #8: NDI: device initialized
10:52:30 Status #9: NDI: tool handles initialized
10:52:30 Status #10: NDI: passive tool handles enabled 
10:52:46 Status #11: NDI: tracking is on
10:52:46 Error #1: NDI: parsing TX result failed, expected line feed
10:52:47 Status #12: NDI: tracking is off
10:52:56 Status #13: NDI: tracking is on
10:52:56 Error #2: NDI: parsing TX result failed, expected line feed
10:52:57 Status #14: NDI: tracking is off

Thank you very much in advance.
Best regards
Moe

**Comment by adeguet1** [comment]
It’s a bit hard to debug without the device handy.   Do you happen to be a Johns Hopkins user?   Is so I can come to take a look.   Otherwise, you can start the ROS node with the command line option “-l” to log all the serial port communications  in the file cisstLog.txt.   This might help to debug the issue.

Anton

---
Anton Deguet
Associate Research Scientist
www.lcsr.jhu.edu - www.malonecenter.jhu.edu

**Comment by ScottyChung** [comment]
We had a similar issue that was related to the new tool type. The commit on the dev branch (3b4ca046342d2bc79b39e9724c456d5f3c81145a) corrected the problem.

**Comment by moe-sani** [comment]
Hi adeguet1,
Thanks for quick reply. Sorry I was on a tip.

No I am not in Hopkins... I am in the UK.
OK, I will try the suggested options and will let you know.

@ScottyChung Thanks! I hope this works for me as well. I will let you know.

Regards
Moe
