### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by ScottyChung** [jhu-saw/sawNDITracker#8]
Attempting to run after fd0ab778bf13a9aec917a062c0d30c8fd6a108da is causing an error. Compiling seems normal

Contents of cisstlog with -l.
> M- cisst 1.0.11 (git: 1.0.11-1-g4237673)
M- CISST_ROOT: undefined
M- cisst share: undefined
M- cmn_m: 1, cmn_kg: 1, CISST_USE_SI_UNITS is set to 1
M- Class cmnClassRegister: SetLogMaskClassMatching: log LoD has been set to "-D -M -W -E D- M- W- E- " for the following classes matching "mtsNDISerial": mtsNDISerial, mtsNDISerialControllerQtWidget,
M- osaThread::CreateInternal: create thread named: Unnamed
M- osaThread::CreateInternal: create thread named: Unnamed

**Comment by adeguet1** [comment]
Sorry about that.   Can you upload  the JSON config file you’re using?

---

On Oct 22, 2019, at 11:50, Scotty <notifications@github.com> wrote:

﻿

Attempting to run after fd0ab77<https://github.com/jhu-saw/sawNDITracker/commit/fd0ab778bf13a9aec917a062c0d30c8fd6a108da> is causing an error. Compiling seems normal

Contents of cisstlog with -l.

M- cisst 1.0.11 (git: 1.0.11-1-g4237673)
M- CISST_ROOT: undefined
M- cisst share: undefined
M- cmn_m: 1, cmn_kg: 1, CISST_USE_SI_UNITS is set to 1
M- Class cmnClassRegister: SetLogMaskClassMatching: log LoD has been set to "-D -M -W -E D- M- W- E- " for the following classes matching "mtsNDISerial": mtsNDISerial, mtsNDISerialControllerQtWidget,
M- osaThread::CreateInternal: create thread named: Unnamed
M- osaThread::CreateInternal: create thread named: Unnamed

**Comment by ScottyChung** [comment]
It errors both when passing a config file and without. 

[ndi_reference.json.txt](https://github.com/jhu-saw/sawNDITracker/files/3757176/ndi_reference.txt)

**Comment by adeguet1** [comment]
I don't have access to a computer with compiler and NDi device right now but I think the issue comes from an uninitialize pointer (mStrayMarkersReferenceTool).   I edited the code using GitHub interface.  Can you test to see if this compiles and solves the issue?

**Comment by ScottyChung** [comment]
Same issue :(

[compile and error.txt](https://github.com/jhu-saw/sawNDITracker/files/3757793/compile.and.error.txt)

**Comment by adeguet1** [comment]
I hope to look into this tomorrow.  Which device are you using?  Polaris or Aurora?

**Comment by ScottyChung** [comment]
Aurora. No rush. I just found this when adding my other commit to the end of the devel branch. All runs well off the master.

**Comment by ScottyChung** [comment]
So actually I've been misusing the `catkin build` command it seems `catkin build saw_ndi_tracker` does not pickup new changes. With a proper build, I'm not having any errors anymore. This issue can most likely be closed.
